#using integrated GPU for rendering
#https://wiki.hyprland.org/Configuring/Multi-GPU/
#lspci | \grep -E 'VGA|3D'
#ls -l /dev/dri/by-path
#env = AQ_DRM_DEVICES,/dev/dri/card1 

env = XCURSOR_THEME,catppuccin-mocha-dark-cursors
env = XCURSOR_SIZE,24
env = HYPRCURSOR_THEME,catppuccin-mocha-dark
env = HYPRCURSOR_SIZE,24
