exec-once = uwsm finalize AQ_DRM_DEVICES GDK_BACKEND SDL_VIDEODRIVER CLUTTER_BACKEND QT_QPA_PLATFORM MOZ_ENABLE_WAYLAND EGL_PLATFORM ELECTRON_OZONE_PLATFORM_HINT _JAVA_AWT_WM_NONREPARENTING
exec-once = $easyeffects & $clipboard & $openfreebuds &
exec-once=[workspace 1 silent] sleep 3; $BROWSER & sleep 4; $clock & sleep 1; $filemanager & $telegram &
