exec-once = uwsm finalize 
exec-once = systemctl --user restart xdg-desktop-portal-hyprland.service
exec-once = $easyeffects & $clipboard & $openfreebuds &
exec-once=[workspace 1 silent] sleep 2; $browser & sleep 4; $clock & sleep 1; $filemanager & $telegram &
