# for LUKS encryption with mkinitcpio systemd and sd-encrypt hooks

# UUID - an actual device UUID
# discard - needed for trim to work
## rd.luks.name=UUID=root rd.luks.options=discard root=/dev/mapper/root
